import { StyleSheet } from 'react-native';
import { Theme } from '@/constants/theme';

export const styles = StyleSheet.create({
  safeArea: {
    flex: Theme.layout.full,
    backgroundColor: Theme.colors.backgroundWarmAlt,
  },
  container: {
    flex: Theme.layout.full,
  },
  background: {
    ...StyleSheet.absoluteFillObject,
  },
  profileBackdrop: {
    position: 'absolute',
    width: 378,
    height: 315,
    left: -3,
    top: -3,
  },
  authGlow: {
    position: 'absolute',
    width: Theme.sizes.s250,
    height: Theme.sizes.s250,
    borderRadius: Theme.radius.pill,
    opacity: Theme.opacity.o65,
  },
  authGlowTop: {
    top: -Theme.sizes.s100,
    left: -Theme.sizes.s60,
    backgroundColor: Theme.colors.decorativePeachSoft,
  },
  authGlowBottom: {
    bottom: -Theme.sizes.s120,
    right: -Theme.sizes.s70,
    backgroundColor: Theme.colors.decorativePeachAlt,
  },
  header: {
    paddingHorizontal: Theme.spacing.s20,
    paddingTop: Theme.spacing.s12,
    paddingBottom: Theme.spacing.s8,
  },
  overline: {
    fontSize: Theme.typography.size.s11,
    letterSpacing: Theme.typography.letterSpacing.s3,
    textTransform: 'uppercase',
    color: Theme.colors.textSecondary,
    marginBottom: Theme.spacing.s6,
  },
  title: {
    fontSize: Theme.typography.size.s22,
    fontFamily: Theme.fonts.semiBold,
    color: Theme.colors.text,
  },
  content: {
    paddingHorizontal: Theme.spacing.s20,
    paddingBottom: Theme.sizes.s140,
    gap: Theme.spacing.s16,
  },
  authContent: {
    flexGrow: Theme.layout.full,
    alignItems: 'center',
    paddingHorizontal: Theme.spacing.s24,
    paddingTop: Theme.spacing.s40,
    paddingBottom: Theme.spacing.s40,
    gap: Theme.spacing.s24,
  },
  backButton: {
    alignSelf: 'flex-start',
    paddingVertical: Theme.spacing.s6,
    paddingHorizontal: Theme.spacing.s8,
  },
  backText: {
    fontSize: Theme.typography.size.s13,
    color: Theme.colors.textWarm,
  },
  brandBlock: {
    alignItems: 'center',
    gap: Theme.spacing.s10,
  },
  brandLogo: {
    width: Theme.sizes.s140,
    height: Theme.sizes.s140,
  },
  brandText: {
    fontSize: Theme.typography.size.s24,
    fontFamily: Theme.fonts.brand,
    color: Theme.colors.textWarmStrong,
  },
  authStack: {
    width: Theme.percent.p100,
    alignItems: 'center',
    gap: Theme.spacing.s14,
  },
  authButton: {
    width: Theme.percent.p80,
    minHeight: Theme.sizes.s50,
    borderRadius: Theme.radius.pill,
    borderWidth: Theme.borderWidth.hairline,
    alignItems: 'center',
    justifyContent: 'center',
  },
  authButtonPrimary: {
    backgroundColor: Theme.colors.ctaBackground,
    borderColor: Theme.colors.ctaBorder,
  },
  authButtonWeChat: {
    backgroundColor: Theme.colors.successSurface,
    borderColor: Theme.colors.successBorder,
  },
  authButtonInstitution: {
    backgroundColor: Theme.colors.textWarmStrong,
    borderColor: Theme.colors.textWarmStrong,
  },
  authButtonPressed: {
    transform: [{ scale: Theme.scale.pressedSoft }],
  },
  authButtonText: {
    fontSize: Theme.typography.size.s14,
    fontFamily: Theme.fonts.semiBold,
    color: Theme.colors.textWarmStrong,
  },
  authButtonTextInverse: {
    color: Theme.colors.textInverse,
  },
  guestLink: {
    paddingVertical: Theme.spacing.s4,
  },
  guestText: {
    fontSize: Theme.typography.size.s13,
    color: Theme.colors.textMuted,
  },
  registerHint: {
    fontSize: Theme.typography.size.s12,
    color: Theme.colors.textSecondary,
    textAlign: 'center',
  },
  agreementRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    width: Theme.percent.p80,
    gap: Theme.spacing.s6,
  },
  agreementDot: {
    width: Theme.spacing.s12,
    height: Theme.spacing.s12,
    borderRadius: Theme.radius.r6,
    borderWidth: Theme.borderWidth.hairline,
    borderColor: Theme.colors.borderMuted,
    marginTop: Theme.spacing.s2,
  },
  agreementText: {
    flex: Theme.layout.full,
    fontSize: Theme.typography.size.s11,
    color: Theme.colors.textSecondary,
    lineHeight: Theme.typography.lineHeight.s16,
  },
  agreementLink: {
    color: Theme.colors.textLink,
  },
  authStatus: {
    marginTop: Theme.spacing.s6,
    fontSize: Theme.typography.size.s12,
    color: Theme.colors.textSecondary,
    textAlign: 'center',
  },
  phoneInput: {
    flexDirection: 'row',
    alignItems: 'center',
    width: Theme.percent.p80,
    borderWidth: Theme.borderWidth.hairline,
    borderColor: Theme.colors.borderWarmStrong,
    borderRadius: Theme.radius.pill,
    backgroundColor: Theme.colors.overlayStrong,
    minHeight: Theme.sizes.s50,
  },
  phonePrefix: {
    paddingHorizontal: Theme.spacing.s12,
    fontSize: Theme.typography.size.s13,
    color: Theme.colors.textMuted,
    borderRightWidth: Theme.borderWidth.hairline,
    borderRightColor: Theme.colors.borderWarmStrong,
  },
  phoneInputField: {
    flex: Theme.layout.full,
    paddingHorizontal: Theme.spacing.s12,
    fontSize: Theme.typography.size.s14,
    color: Theme.colors.textWarmStrong,
  },
  ctaButton: {
    width: Theme.percent.p80,
    paddingVertical: Theme.spacing.s12,
    borderRadius: Theme.radius.pill,
    alignItems: 'center',
    backgroundColor: Theme.colors.ctaBackground,
    borderWidth: Theme.borderWidth.hairline,
    borderColor: Theme.colors.ctaBorder,
  },
  ctaButtonDisabled: {
    backgroundColor: Theme.colors.borderWarmAlt,
    borderColor: Theme.colors.borderWarmAlt,
  },
  ctaButtonPressed: {
    transform: [{ scale: Theme.scale.pressedSoft }],
  },
  ctaButtonText: {
    fontSize: Theme.typography.size.s14,
    fontFamily: Theme.fonts.semiBold,
    color: Theme.colors.textWarmStrong,
  },
  ctaButtonTextDisabled: {
    color: Theme.colors.textSecondary,
  },
  codeHint: {
    fontSize: Theme.typography.size.s12,
    color: Theme.colors.textSecondary,
    textAlign: 'center',
  },
  codeRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: Theme.spacing.s12,
  },
  codeBox: {
    width: Theme.sizes.s56,
    height: Theme.sizes.s56,
    borderRadius: Theme.radius.r18,
    borderWidth: Theme.borderWidth.hairline,
    borderColor: Theme.colors.borderWarmStrong,
    backgroundColor: Theme.colors.overlayStrong,
    textAlign: 'center',
    textAlignVertical: 'center',
    fontSize: Theme.typography.size.s20,
    color: Theme.colors.textWarmStrong,
  },
  codeBoxFilled: {
    borderColor: Theme.colors.primary,
  },
  codeBoxFocused: {
    borderColor: Theme.colors.primary,
    backgroundColor: Theme.colors.card,
  },
  codeFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: Theme.percent.p80,
    marginTop: Theme.spacing.s6,
  },
  codeFooterLink: {
    fontSize: Theme.typography.size.s12,
    color: Theme.colors.textLink,
  },
  codeFooterHint: {
    fontSize: Theme.typography.size.s12,
    color: Theme.colors.textSecondary,
  },
  codeFooterHintDisabled: {
    color: Theme.colors.textPlaceholder,
  },
  loadingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.s8,
  },
  loadingText: {
    fontSize: Theme.typography.size.s12,
    color: Theme.colors.textWarmStrong,
  },
  nicknameHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    gap: Theme.spacing.s8,
  },
  nicknameTitle: {
    fontSize: Theme.typography.size.s24,
    fontFamily: Theme.fonts.semiBold,
    color: Theme.colors.textWarmStrong,
  },
  nicknameInput: {
    width: Theme.percent.p80,
    minHeight: Theme.sizes.s50,
    borderRadius: Theme.radius.pill,
    borderWidth: Theme.borderWidth.hairline,
    borderColor: Theme.colors.borderWarmStrong,
    backgroundColor: Theme.colors.overlayStrong,
    paddingHorizontal: Theme.spacing.s16,
    fontSize: Theme.typography.size.s14,
    color: Theme.colors.textWarmStrong,
  },
  wechatCard: {
    width: Theme.percent.p80,
    borderRadius: Theme.radius.r18,
    borderWidth: Theme.borderWidth.hairline,
    borderColor: Theme.colors.borderWarmStrong,
    backgroundColor: Theme.colors.cardTranslucentSoft,
    paddingVertical: Theme.spacing.s20,
    paddingHorizontal: Theme.spacing.s16,
    alignItems: 'center',
    gap: Theme.spacing.s10,
  },
  wechatTitle: {
    fontSize: Theme.typography.size.s16,
    fontFamily: Theme.fonts.semiBold,
    color: Theme.colors.text,
  },
  wechatHint: {
    fontSize: Theme.typography.size.s12,
    color: Theme.colors.textSecondary,
  },
  institutionHint: {
    fontSize: Theme.typography.size.s14,
    color: Theme.colors.textSecondary,
  },
  institutionInput: {
    width: Theme.percent.p80,
    minHeight: Theme.sizes.s50,
    borderRadius: Theme.radius.pill,
    borderWidth: Theme.borderWidth.hairline,
    borderColor: Theme.colors.borderWarmStrong,
    backgroundColor: Theme.colors.overlayStrong,
    paddingHorizontal: Theme.spacing.s16,
    fontSize: Theme.typography.size.s14,
    color: Theme.colors.textWarmStrong,
  },
  institutionTip: {
    fontSize: Theme.typography.size.s12,
    color: Theme.colors.textSecondary,
  },
  profileCard: {
    marginTop: Theme.spacing.s8,
    padding: Theme.spacing.s20,
    alignItems: 'center',
  },
  avatarWrap: {
    width: Theme.sizes.s96,
    height: Theme.sizes.s96,
    borderRadius: Theme.radius.r48,
    backgroundColor: Theme.colors.surfaceWarm,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: Theme.spacing.s12,
    borderWidth: Theme.borderWidth.hairline,
    borderColor: Theme.colors.borderWarmSoft,
  },
  avatarPressed: {
    transform: [{ scale: Theme.scale.pressedSoft }],
  },
  avatar: {
    width: Theme.sizes.s68,
    height: Theme.sizes.s68,
  },
  name: {
    fontSize: Theme.typography.size.s20,
    fontFamily: Theme.fonts.semiBold,
    color: Theme.colors.text,
  },
  nicknameLabel: {
    marginTop: Theme.spacing.s12,
    fontSize: Theme.typography.size.s12,
    color: Theme.colors.textSecondary,
    textTransform: 'uppercase',
    letterSpacing: Theme.typography.letterSpacing.s1_6,
  },
  nicknamePill: {
    marginTop: Theme.spacing.s6,
    paddingHorizontal: Theme.spacing.s14,
    paddingVertical: Theme.spacing.s6,
    borderRadius: Theme.radius.pill,
    backgroundColor: Theme.colors.successSurface,
    borderWidth: Theme.borderWidth.hairline,
    borderColor: Theme.colors.successBorder,
  },
  nicknameText: {
    fontSize: Theme.typography.size.s14,
    color: Theme.colors.successStrong,
    fontFamily: Theme.fonts.semiBold,
  },
  userTypePill: {
    marginTop: Theme.spacing.s6,
    paddingHorizontal: Theme.spacing.s14,
    paddingVertical: Theme.spacing.s6,
    borderRadius: Theme.radius.pill,
    backgroundColor: Theme.colors.warningSurface,
    borderWidth: Theme.borderWidth.hairline,
    borderColor: Theme.colors.warningBorder,
  },
  userTypeText: {
    fontSize: Theme.typography.size.s13,
    color: Theme.colors.warningText,
    fontFamily: Theme.fonts.semiBold,
  },
  emailText: {
    marginTop: Theme.spacing.s10,
    fontSize: Theme.typography.size.s13,
    color: Theme.colors.textSecondary,
  },
  statusText: {
    fontSize: Theme.typography.size.s13,
    color: Theme.colors.textEmphasis,
  },
  sectionCard: {
    padding: Theme.spacing.s18,
    backgroundColor: Theme.colors.cardTranslucentSoft,
    borderRadius: Theme.radius.r20,
    borderWidth: Theme.borderWidth.hairline,
    borderColor: Theme.colors.borderWarm,
    gap: Theme.spacing.s12,
    ...Theme.shadows.cardSoftLarge,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sectionTitle: {
    fontSize: Theme.typography.size.s16,
    fontFamily: Theme.fonts.semiBold,
    color: Theme.colors.text,
  },
  sectionSubtitle: {
    fontSize: Theme.typography.size.s12,
    color: Theme.colors.textSecondary,
  },
  adoptionList: {
    gap: Theme.spacing.s16,
  },
  adoptionItem: {
    gap: Theme.spacing.s10,
  },
  adoptionMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.s8,
  },
  adoptionMetaLabel: {
    fontSize: Theme.typography.size.s12,
    color: Theme.colors.textSecondary,
  },
  adoptionMetaPill: {
    paddingHorizontal: Theme.spacing.s10,
    paddingVertical: Theme.spacing.s2,
    borderRadius: Theme.radius.pill,
    backgroundColor: Theme.colors.surfaceWarm,
    borderWidth: Theme.borderWidth.hairline,
    borderColor: Theme.colors.borderWarmSoft,
  },
  adoptionMetaText: {
    fontSize: Theme.typography.size.s12,
    color: Theme.colors.textWarm,
    fontFamily: Theme.fonts.semiBold,
  },
  petsList: {
    gap: Theme.spacing.s12,
  },
  emptyText: {
    fontSize: Theme.typography.size.s13,
    color: Theme.colors.textSecondary,
  },
  errorText: {
    fontSize: Theme.typography.size.s13,
    color: Theme.colors.textError,
  },
  formCard: {
    padding: Theme.spacing.s18,
    backgroundColor: Theme.colors.cardTranslucentSoft,
    borderRadius: Theme.radius.r20,
    borderWidth: Theme.borderWidth.hairline,
    borderColor: Theme.colors.borderWarm,
    ...Theme.shadows.elevatedSoft,
  },
  formTitle: {
    fontSize: Theme.typography.size.s16,
    fontFamily: Theme.fonts.semiBold,
    color: Theme.colors.text,
    marginBottom: Theme.spacing.s12,
  },
  formSubtitle: {
    fontSize: Theme.typography.size.s13,
    color: Theme.colors.textSecondary,
    marginBottom: Theme.spacing.s12,
  },
  actionButton: {
    backgroundColor: Theme.colors.ctaBackground,
    borderWidth: Theme.borderWidth.hairline,
    borderColor: Theme.colors.ctaBorder,
    paddingVertical: Theme.spacing.s12,
    borderRadius: Theme.radius.r14,
    alignItems: 'center',
  },
  actionButtonPressed: {
    transform: [{ scale: Theme.scale.pressedSoft }],
  },
  actionButtonText: {
    color: Theme.colors.ctaText,
    fontSize: Theme.typography.size.s14,
    fontFamily: Theme.fonts.semiBold,
  },
  institutionFab: {
    position: 'absolute',
    right: Theme.spacing.s20,
    bottom: Theme.sizes.s120,
    width: Theme.sizes.s56,
    height: Theme.sizes.s56,
    borderRadius: Theme.sizes.s56 / 2,
    backgroundColor: Theme.colors.successDeep,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: Theme.borderWidth.hairline,
    borderColor: Theme.colors.successDeep,
    ...Theme.shadows.card,
  },
  institutionFabPressed: {
    transform: [{ scale: Theme.scale.pressedSoft }],
  },
});
